// Mocks generated by Mockito 5.4.4 from annotations
// in baryabest_app/test/features/search/search_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:baryabest_app/models/affiliate_product.dart' as _i5;
import 'package:baryabest_app/services/search_service.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i3.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<List<_i5.AffiliateProduct>> search({
    required String? platform,
    required String? query,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [],
          {
            #platform: platform,
            #query: query,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue: _i4.Future<List<_i5.AffiliateProduct>>.value(
            <_i5.AffiliateProduct>[]),
      ) as _i4.Future<List<_i5.AffiliateProduct>>);
}
