<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Returns mock homepage sections to power the app homepage.
     */
    public function home(Request $request)
    {
        $sections = [
            [
                'title' => 'Flash Deals 🔥',
                'items' => [
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2001',
                        'title' => 'Wireless Bluetooth Earbuds TWS 5.0 with Charging Case',
                        'price' => 799.00,
                        'original_price' => 1299.00,
                        'discount' => 0.38,
                        'rating' => 4.8,
                        'review_count' => 15420,
                        'seller_rating' => 4.9,
                        'sales' => 50000,
                        'image' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/earbuds-tws?aff_id=MOCK_SHOPEE',
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                    [
                        'platform' => 'lazada',
                        'platform_product_id' => 'LZ-1003',
                        'title' => 'Apple AirPods Pro 2nd Generation with MagSafe',
                        'price' => 13499.00,
                        'original_price' => 14990.00,
                        'discount' => 0.10,
                        'rating' => 4.9,
                        'review_count' => 5678,
                        'seller_rating' => 5.0,
                        'sales' => 25000,
                        'image' => 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.lazada.com.ph/products/airpods-pro?aff_id=MOCK_LAZADA',
                        'data_source' => 'Data provided via Lazada Affiliate API',
                    ],
                    [
                        'platform' => 'tiktok',
                        'platform_product_id' => 'TT-3004',
                        'title' => 'Snail Mucin 96% Power Repairing Essence 100ml',
                        'price' => 699.00,
                        'original_price' => 999.00,
                        'discount' => 0.30,
                        'rating' => 4.9,
                        'review_count' => 23450,
                        'seller_rating' => 4.9,
                        'sales' => 180000,
                        'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.tiktok.com/shop/snail-mucin?aff_id=MOCK_TIKTOK',
                        'data_source' => 'Data provided via TikTok Shop Affiliate API',
                    ],
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2004',
                        'title' => 'Portable Power Bank 20000mAh Fast Charge PD 65W',
                        'price' => 1299.00,
                        'original_price' => 1999.00,
                        'discount' => 0.35,
                        'rating' => 4.9,
                        'review_count' => 5820,
                        'seller_rating' => 4.9,
                        'sales' => 35000,
                        'image' => 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/power-bank?aff_id=MOCK_SHOPEE',
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                ],
            ],
            [
                'title' => 'Trending Now 📈',
                'items' => [
                    ['query' => 'wireless earbuds', 'icon' => '🎧'],
                    ['query' => 'ring light', 'icon' => '💡'],
                    ['query' => 'skincare', 'icon' => '✨'],
                    ['query' => 'sneakers', 'icon' => '👟'],
                    ['query' => 'smartwatch', 'icon' => '⌚'],
                    ['query' => 'air fryer', 'icon' => '🍳'],
                ],
            ],
            [
                'title' => 'Best from Shopee 🛒',
                'items' => [
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2005',
                        'title' => 'Korean Style Oversized T-Shirt Unisex Cotton',
                        'price' => 199.00,
                        'original_price' => 399.00,
                        'discount' => 0.50,
                        'rating' => 4.5,
                        'review_count' => 12300,
                        'seller_rating' => 4.6,
                        'sales' => 85000,
                        'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/oversized-tshirt?aff_id=MOCK_SHOPEE',
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2013',
                        'title' => 'Smart Watch Fitness Tracker Heart Rate Monitor',
                        'price' => 1499.00,
                        'original_price' => 2499.00,
                        'discount' => 0.40,
                        'rating' => 4.7,
                        'review_count' => 7650,
                        'seller_rating' => 4.8,
                        'sales' => 55000,
                        'image' => 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/smart-watch?aff_id=MOCK_SHOPEE',
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2015',
                        'title' => 'Mechanical Gaming Keyboard RGB Backlit Blue Switch',
                        'price' => 1299.00,
                        'original_price' => 1999.00,
                        'discount' => 0.35,
                        'rating' => 4.8,
                        'review_count' => 2890,
                        'seller_rating' => 4.9,
                        'sales' => 22000,
                        'image' => 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/gaming-keyboard?aff_id=MOCK_SHOPEE',
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                ],
            ],
            [
                'title' => 'Top Picks from Lazada 🏷️',
                'items' => [
                    [
                        'platform' => 'lazada',
                        'platform_product_id' => 'LZ-1001',
                        'title' => 'Sony Wireless Noise Cancelling Headphones WH-1000XM5',
                        'price' => 15999.00,
                        'original_price' => 19999.00,
                        'discount' => 0.20,
                        'rating' => 4.9,
                        'review_count' => 3254,
                        'seller_rating' => 4.9,
                        'sales' => 12000,
                        'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.lazada.com.ph/products/sony-headphones?aff_id=MOCK_LAZADA',
                        'data_source' => 'Data provided via Lazada Affiliate API',
                    ],
                    [
                        'platform' => 'lazada',
                        'platform_product_id' => 'LZ-1005',
                        'title' => 'Nike Air Force 1 07 White Sneakers Original',
                        'price' => 5495.00,
                        'original_price' => 5795.00,
                        'discount' => 0.05,
                        'rating' => 4.8,
                        'review_count' => 4521,
                        'seller_rating' => 4.9,
                        'sales' => 32000,
                        'image' => 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.lazada.com.ph/products/nike-air-force?aff_id=MOCK_LAZADA',
                        'data_source' => 'Data provided via Lazada Affiliate API',
                    ],
                    [
                        'platform' => 'lazada',
                        'platform_product_id' => 'LZ-1010',
                        'title' => 'Philips Air Fryer XXL Premium HD9861 Digital',
                        'price' => 12999.00,
                        'original_price' => 15999.00,
                        'discount' => 0.19,
                        'rating' => 4.8,
                        'review_count' => 1876,
                        'seller_rating' => 4.9,
                        'sales' => 9800,
                        'image' => 'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.lazada.com.ph/products/philips-airfryer?aff_id=MOCK_LAZADA',
                        'data_source' => 'Data provided via Lazada Affiliate API',
                    ],
                ],
            ],
            [
                'title' => 'Viral on TikTok 🎵',
                'items' => [
                    [
                        'platform' => 'tiktok',
                        'platform_product_id' => 'TT-3008',
                        'title' => 'Cloud Slippers Soft Pillow Slides Indoor Outdoor',
                        'price' => 299.00,
                        'original_price' => 499.00,
                        'discount' => 0.40,
                        'rating' => 4.8,
                        'review_count' => 34560,
                        'seller_rating' => 4.9,
                        'sales' => 320000,
                        'image' => 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.tiktok.com/shop/cloud-slippers?aff_id=MOCK_TIKTOK',
                        'data_source' => 'Data provided via TikTok Shop Affiliate API',
                    ],
                    [
                        'platform' => 'tiktok',
                        'platform_product_id' => 'TT-3001',
                        'title' => 'LED Ring Light 10 inch with Tripod Stand Phone Holder',
                        'price' => 549.00,
                        'original_price' => 899.00,
                        'discount' => 0.39,
                        'rating' => 4.7,
                        'review_count' => 12450,
                        'seller_rating' => 4.8,
                        'sales' => 89000,
                        'image' => 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.tiktok.com/shop/ring-light?aff_id=MOCK_TIKTOK',
                        'data_source' => 'Data provided via TikTok Shop Affiliate API',
                    ],
                    [
                        'platform' => 'tiktok',
                        'platform_product_id' => 'TT-3010',
                        'title' => 'Sunset Lamp Projector Rainbow Atmosphere Light',
                        'price' => 399.00,
                        'original_price' => 699.00,
                        'discount' => 0.43,
                        'rating' => 4.4,
                        'review_count' => 6780,
                        'seller_rating' => 4.5,
                        'sales' => 48000,
                        'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.tiktok.com/shop/sunset-lamp?aff_id=MOCK_TIKTOK',
                        'data_source' => 'Data provided via TikTok Shop Affiliate API',
                    ],
                ],
            ],
            [
                'title' => 'AI Recommendations ✨',
                'items' => [
                    [
                        'platform' => 'shopee',
                        'platform_product_id' => 'SP-2011',
                        'title' => 'Facial Cleanser Foam Gentle Deep Clean 150ml',
                        'price' => 189.00,
                        'original_price' => 299.00,
                        'discount' => 0.37,
                        'rating' => 4.8,
                        'review_count' => 9870,
                        'seller_rating' => 4.9,
                        'sales' => 78000,
                        'image' => 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://shopee.ph/product/facial-cleanser?aff_id=MOCK_SHOPEE',
                        'ai_recommendation' => [
                            'recommended_price' => 175.00,
                            'confidence' => 0.89,
                            'reason' => 'Best seller with consistent 5-star reviews',
                        ],
                        'data_source' => 'Data provided via Shopee Affiliate API',
                    ],
                    [
                        'platform' => 'lazada',
                        'platform_product_id' => 'LZ-1013',
                        'title' => 'Estee Lauder Advanced Night Repair Serum 50ml',
                        'price' => 5499.00,
                        'original_price' => 6500.00,
                        'discount' => 0.15,
                        'rating' => 4.9,
                        'review_count' => 4532,
                        'seller_rating' => 4.9,
                        'sales' => 35000,
                        'image' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=300&h=300&fit=crop',
                        'affiliate_url' => 'https://www.lazada.com.ph/products/estee-lauder-serum?aff_id=MOCK_LAZADA',
                        'ai_recommendation' => [
                            'recommended_price' => 5200.00,
                            'confidence' => 0.92,
                            'reason' => 'Premium brand with high resale value',
                        ],
                        'data_source' => 'Data provided via Lazada Affiliate API',
                    ],
                ],
            ],
        ];

        return response()->json([
            'app' => config('app.name', 'BaryaBest'),
            'sections' => $sections,
            'attribution' => 'Data provided via partner affiliate APIs.',
        ]);
    }
}
